[package]
name = "api"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "santi-api"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
plumb.workspace = true
santi-api.workspace = true
santi-core.workspace = true
santi-estate.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
async-trait.workspace = true
futures-util.workspace = true
santi-estate.workspace = true
santi-provider.workspace = true
sha2.workspace = true
tempfile = "3.27.0"
uuid.workspace = true
